apiVersion: apps/v1
kind: Deployment
metadata:
  name: frasberg-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frasberg-engine
  template:
    metadata:
      labels:
        app: frasberg-engine
    spec:
      containers:
        - name: engine
          image: '{{ .Values.image.engine }}:{{ .Values.image.tag }}'
          ports:
            - containerPort: 4002
