#!/bin/bash
echo "═══ Submit to arXiv ═══"
echo ""
echo "1. Create account: https://arxiv.org/user/register"
echo "2. Convert to PDF:"
echo "   pandoc PAPER.md -o paper.pdf --citeproc"
echo ""
echo "3. Upload to arXiv:"
echo "   - Category: cs.DC (Distributed Computing)"
echo "   - Secondary: cs.ET (Emerging Technologies)"
echo "   - Add supplementary: Link to GitHub"
echo ""
echo "4. Target Conferences:"
echo "   - NeurIPS 2026 (Deadline: May 2026)"
echo "   - ICML 2026 (Deadline: Feb 2026)"
echo "   - SOSP 2026 (Deadline: Apr 2026)"
