#!/bin/bash
# Research Paper Submission Script for Frasberg DNA Computing Paper

set -e

echo "╔════════════════════════════════════════════════════════╗"
echo "║  Frasberg DNA Computing Paper Submission Helper     ║"
echo "╚════════════════════════════════════════════════════════╝"
echo ""

# Check if paper exists
if [ ! -f "paper.md" ]; then
    echo "❌ Error: paper.md not found in current directory"
    echo "   Run this script from research/papers/dna-computing/"
    exit 1
fi

echo "📄 Paper: DNA Computing Integration in Distributed Intelligence Systems"
echo ""

echo "═══════════════════════════════════════════════════════"
echo "  TARGET CONFERENCES & JOURNALS"
echo "═══════════════════════════════════════════════════════"
echo ""

echo "🏆 TIER 1 - Top AI/ML Conferences:"
echo "  • NeurIPS 2026"
echo "    Deadline: May 2026"
echo "    URL: https://neurips.cc/"
echo "    Focus: Novel computational paradigms"
echo ""
echo "  • ICML 2026"
echo "    Deadline: February 2026 (⚠️  SOON!)"
echo "    URL: https://icml.cc/"
echo "    Focus: Machine learning systems"
echo ""
echo "  • ICLR 2027"
echo "    Deadline: September 2026"
echo "    URL: https://iclr.cc/"
echo "    Focus: Learning representations"
echo ""

echo "🔬 TIER 1 - Systems Conferences:"
echo "  • SOSP 2026 (Systems)"
echo "    Deadline: April 2026"
echo "    Focus: Operating systems, distributed systems"
echo ""
echo "  • OSDI 2026 (Systems Design)"
echo "    Deadline: December 2026"
echo "    Focus: Implementation and evaluation"
echo ""
echo "  • SIGMOD 2026 (Data Systems)"
echo "    Deadline: September 2025 (passed, target 2027)"
echo "    Focus: Novel storage systems"
echo ""

echo "🧬 Domain-Specific Conferences:"
echo "  • DNA Computing Conference 2026"
echo "    Deadline: TBD (typically March)"
echo "    URL: http://www.dna-computing.org/"
echo "    Focus: Pure DNA computing research"
echo ""
echo "  • ISMB 2026 (Bioinformatics)"
echo "    Deadline: January 2026"
echo "    Focus: Computational biology"
echo ""

echo "📚 High-Impact Journals:"
echo "  • Nature Biotechnology"
echo "    Rolling submissions"
echo "    Impact Factor: 68.2"
echo ""
echo "  • Science (Research Articles)"
echo "    Rolling submissions"
echo "    Impact Factor: 56.9"
echo ""
echo "  • Nature Communications"
echo "    Rolling submissions"
echo "    Impact Factor: 16.6"
echo "    Open Access option available"
echo ""

echo "🌐 Open Access / Preprint:"
echo "  • arXiv.org (Computer Science)"
echo "    Immediate submission"
echo "    Section: cs.DC (Distributed Computing) or cs.ET (Emerging Technologies)"
echo ""
echo "  • bioRxiv.org (Biology)"
echo "    Immediate submission"
echo "    Section: Synthetic Biology"
echo ""

echo ""
echo "═══════════════════════════════════════════════════════"
echo "  RECOMMENDED SUBMISSION STRATEGY"
echo "═══════════════════════════════════════════════════════"
echo ""

echo "Phase 1 (IMMEDIATE): Preprint Distribution"
echo "  1. Post to arXiv.org (cs.DC + cs.ET)"
echo "  2. Post to bioRxiv.org (if wet-lab data available)"
echo "  3. Share on Twitter, Reddit (r/MachineLearning, r/compsci)"
echo "  4. Submit to HackerNews"
echo ""

echo "Phase 2 (February 2026): Conference Submission"
echo "  Primary target: ICML 2026 (deadline: Feb 2026)"
echo "  Backup: NeurIPS 2026 (deadline: May 2026)"
echo ""

echo "Phase 3 (If accepted): Camera-ready + presentation"
echo "  If rejected: Revise based on feedback, target SOSP/OSDI"
echo ""

echo "Phase 4 (Post-conference): Journal submission"
echo "  Target: Nature Communications (open access)"
echo "  Include conference feedback and additional experiments"
echo ""

echo "═══════════════════════════════════════════════════════"
echo "  NEXT STEPS"
echo "═══════════════════════════════════════════════════════"
echo ""

echo "Before Submission Checklist:"
echo "  ☐ Complete wet-lab validation (or clearly state simulation-only)"
echo "  ☐ Run all benchmarks and collect data"
echo "  ☐ Create figures and tables"
echo "  ☐ Proofread for typos and clarity"
echo "  ☐ Have colleagues review"
echo "  ☐ Check paper length limits (ICML: 8 pages + refs)"
echo "  ☐ Format according to conference template"
echo "  ☐ Prepare supplementary materials"
echo "  ☐ Write compelling abstract (250 words)"
echo ""

echo "To submit to arXiv NOW:"
echo "  1. Create account at https://arxiv.org/user/register"
echo "  2. Convert paper.md to LaTeX or PDF"
echo "  3. Upload via https://arxiv.org/submit"
echo "  4. Choose categories: cs.DC (primary), cs.ET, q-bio.MN"
echo "  5. Add this GitHub repo URL in comments"
echo ""

echo "═══════════════════════════════════════════════════════"
echo "  RESOURCES"
echo "═══════════════════════════════════════════════════════"
echo ""
echo "LaTeX Template: Download from ICML website"
echo "Paper Length: ICML: 8 pages (+ unlimited refs/appendix)"
echo "Review Process: Double-blind (remove author names)"
echo "Review Time: ~3 months for conferences"
echo ""

echo "Questions? Email: research@frasberg.ai"
echo ""

# Offer to convert to LaTeX
echo "Would you like help converting to LaTeX format? (y/n)"
read -r response

if [[ "$response" =~ ^[Yy]$ ]]; then
    echo ""
    echo "Converting to LaTeX..."
    echo ""
    echo "Recommended tool: Pandoc"
    echo "  Install: sudo apt-get install pandoc"
    echo "  Convert: pandoc paper.md -o paper.tex"
    echo ""
    echo "Or use Overleaf.com (online LaTeX editor)"
    echo "  1. Create account at overleaf.com"
    echo "  2. New Project → Upload paper.md"
    echo "  3. Choose ICML template"
    echo "  4. Convert Markdown to LaTeX"
fi

echo ""
echo "✅ Submission helper complete!"
echo ""
