export enum ErrorCode {
  KEY_NOT_FOUND = 'KEY_NOT_FOUND',
  KEY_NOT_PROVIDED = 'KEY_NOT_PROVIDED',
  KEY_DISABLED = 'KEY_DISABLED',

  OWNER_NOT_FOUND = 'OWNER_NOT_FOUND',
  INVALID_OWNER_ID = 'INVALID_OWNER_ID',

  WORKSPACE_NOT_FOUND = 'WORKSPACE_NOT_FOUND',
  INVALID_WORKSPACE_ID = 'INVALID_WORKSPACE_ID',

  PERMISSION_DENIED = 'PERMISSION_DENIED',
  ACCOUNT_SUSPENDED = 'ACCOUNT_SUSPENDED',

  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  QUOTA_EXCEEDED = 'QUOTA_EXCEEDED',
  RATE_LIMIT_FAILURE = 'RATE_LIMIT_FAILURE',
  RATE_LIMIT_SERVICE_UNAVAILABLE = 'RATE_LIMIT_SERVICE_UNAVAILABLE',

  MODEL_NOT_FOUND = 'MODEL_NOT_FOUND',
  MODEL_UNAVAILABLE = 'MODEL_UNAVAILABLE',
  RUNTIME_UNAVAILABLE = 'RUNTIME_UNAVAILABLE',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',

  INTERNAL_ERROR = 'INTERNAL_ERROR',
  AUTH_FAILURE = 'AUTH_FAILURE',
}
