version: "3.9"
services:
  analytics:
    build:
      context: ../..
      dockerfile: deploy/analytics/Dockerfile
    container_name: frasberg_analytics
    ports:
      - "5000:5000"
    environment:
      - SERVICE_NAME=analytics
      - DATA_TYPE=meta-only
    restart: unless-stopped
