export const SERVICES = [
  'auth',
  'compute',
  'core',
  'data',
  'queue',
  'cache',
  'search',
  'events',
  'notify',
  'billing',
  'identity',
  'profile',
  'preferences',
  'sessions',
  'state',
  'presence',
  'activity',
  'history',
  'timeline',
  'feed',
  'stream',
  'sync',
  'merge',
  'aggregate',
  'reduce',
  'fold',
  'compress',
  'pack',
  'bundle',
  'wrap',
  'seal',
  'finalize',
  'deliver',
  'dispatch',
  'route',
  'relay',
  'transmit',
  'broadcast',
  'multicast',
  'fanout',
  'spread',
  'diffuse',
  'propagate',
  'radiate',
  'beam',
  'pulse',
  'wave',
  'ripple',
  'echo',
  'resonate',
  'amplify',
  'boost',
  'surge',
  'flare',
  'flash',
] as const;

export type FrasbergService = (typeof SERVICES)[number];

export const serviceMap: Record<FrasbergService, string> = Object.fromEntries(
  SERVICES.map((svc) => [`${svc}`, `https://${svc}.aws.frasberg.com`]),
) as Record<FrasbergService, string>;

export function isFrasbergService(
  name: string,
): name is FrasbergService {
  return (SERVICES as readonly string[]).includes(name);
}
