apiVersion: apps/v1
kind: Deployment
metadata:
  name: luchii-us-east
  labels:
    app: luchii
    region: us-east
spec:
  replicas: 3
  selector:
    matchLabels:
      app: luchii
      region: us-east
  template:
    metadata:
      labels:
        app: luchii
        region: us-east
    spec:
      containers:
        - name: luchii
          image: ghcr.io/frasbergai/luchii-engine:latest
          ports:
            - containerPort: 9000
          env:
            - name: REGION
              value: "us-east"
---
apiVersion: v1
kind: Service
metadata:
  name: luchii-us-east
spec:
  selector:
    app: luchii
    region: us-east
  ports:
    - port: 9000
      targetPort: 9000