apiVersion: apps/v1
kind: Deployment
metadata:
  name: luchii-eu-central
  labels:
    app: luchii
    region: eu-central
spec:
  replicas: 3
  selector:
    matchLabels:
      app: luchii
      region: eu-central
  template:
    metadata:
      labels:
        app: luchii
        region: eu-central
    spec:
      containers:
        - name: luchii
          image: ghcr.io/frasbergai/luchii-engine:latest
          ports:
            - containerPort: 9000
          env:
            - name: REGION
              value: "eu-central"
---
apiVersion: v1
kind: Service
metadata:
  name: luchii-eu-central
spec:
  selector:
    app: luchii
    region: eu-central
  ports:
    - port: 9000
      targetPort: 9000