import { runGT6Orchestrator } from '../gt6/gt6-orchestrator';
import { enforceCostCeiling } from './costGovernor';
import { recover } from './errorRecovery';
import { EmergentAgentRuntime } from './emergentAgentRuntime';
import { recordTimelineEvent, TimelineEventType } from './jobTimeline';

export class EmergentAgentOrchestrator {
  constructor(private readonly runtime: EmergentAgentRuntime) {}

  async handle(request: any, jobId: string = request.raceConfig.raceId) {
    const planned = runGT6Orchestrator(request);
    const plan = enforceCostCeiling(planned, request.maxCostWeight ?? Infinity);

    const outputs: any = {
      enginesUsed: plan.enginesUsed,
      raceState: plan.raceState,
      aiDecisions: plan.aiDecisions,
      physicsStep: plan.physicsStep,
      multimodal: {},
      recovered: [] as any[],
    };

    const run = async (
      engine: TimelineEventType,
      key: string,
      call: () => Promise<any>,
    ) => {
      recordTimelineEvent({
        id: `${engine}-${jobId}-running`,
        jobId,
        type: engine,
        status: 'running',
        timestamp: Date.now(),
      });
      try {
        const result = await call();
        const failed = result?.status === 'failed';
        outputs.multimodal[key] = result;
        if (failed) {
          outputs.recovered.push({ engine, ...recover(new Error(result.error)) });
        }
        recordTimelineEvent({
          id: `${engine}-${jobId}-done`,
          jobId,
          type: engine,
          status: failed ? 'failed' : 'completed',
          timestamp: Date.now(),
          meta: failed ? { error: result.error } : undefined,
        });
      } catch (error) {
        outputs.recovered.push({ engine, ...recover(error) });
        recordTimelineEvent({
          id: `${engine}-${jobId}-done`,
          jobId,
          type: engine,
          status: 'failed',
          timestamp: Date.now(),
          meta: { error: (error as Error).message },
        });
      }
    };

    for (const engine of plan.enginesUsed as string[]) {
      if (engine === 'video') {
        await run('video', 'video', () =>
          this.runtime.video({ raceState: plan.raceState }),
        );
      }
      if (engine === 'music') {
        await run('music', 'music', () =>
          this.runtime.music({ raceState: plan.raceState }),
        );
      }
      if (engine === 'voice') {
        await run('voice', 'voice', () =>
          this.runtime.voice('Race commentary generated by emergentAgent'),
        );
      }
      if (engine === 'image') {
        await run('image', 'image', () =>
          this.runtime.image({ raceState: plan.raceState }),
        );
      }
    }

    return outputs;
  }
}
