name: Studio CI

on:
  pull_request:
    paths:
      - 'studio/**'
  push:
    paths:
      - 'studio/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: studio
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npm run build